spring.jpa.hibernate.ddl-auto: create-drop
spring.application.name: adminux
spring.jpa.open-in-view: true

spring:
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true