spring.jpa.hibernate.ddl-auto: none
spring.application.name: adminux
spring.jpa.open-in-view: true
#spring.jpa.defer-datasource-initialization: false

#liquibase:
#  change-log: classpath:/db/changelog/db.changelog-master.yaml

spring:
  datasource:
    url: jdbc:h2:mem:adminux
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  url: jdbc:h2:mem:adminux
  user: sa
  password: sa

logging.level:
  root: info
  org.h2: trace
  com.zaxxer: trace
  liquibase: trace

com.net128.lib.spring.jpa.csv.util:
  title-format-regex: >
    Perc$; %,
    perSqKm$;/㎢,
    SqKm; ㎢,
    Change$; Δ,
    Change %; Δ%,
    popPer;pop. /,
    popUrban;pop.urban,
    population; population,
    countryNameEn;country (EN),
    modificationDate;mod.date,
    medAge;age x̄
