spring.jpa.hibernate.ddl-auto: create-drop
spring.application.name: adminux
spring.jpa.open-in-view: true
spring.jpa.defer-datasource-initialization: true

spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true