spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-nName: org.postgresql.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect