spring:
  datasource:
    url: jdbc:mysql://localhost:13306/db?useUnicode=true&characterEncoding=UTF-8
    username: mysql
    password: mysql
    driver-class-nName: com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect