version: '3.8'
services:
  adminux-pg:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '15432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    container_name: adminux-pg
volumes:
  db:
    driver: local